const elements = [
  {symbol:"H",name:"Hydrogen",number:1,group:1,period:1,category:"Reactive nonmetals",info:"Lightest element.",atomicRadius:53,electronegativity:2.20},
  {symbol:"He",name:"Helium",number:2,group:18,period:1,category:"Noble gases",info:"Noble gas.",atomicRadius:31,electronegativity:null},
  {symbol:"Li",name:"Lithium",number:3,group:1,period:2,category:"Alkali metals",info:"Used in batteries.",atomicRadius:167,electronegativity:0.98},
  {symbol:"Be",name:"Beryllium",number:4,group:2,period:2,category:"Alkaline earth metals",info:"Light metal.",atomicRadius:112,electronegativity:1.57},
  {symbol:"B",name:"Boron",number:5,group:13,period:2,category:"Metalloids",info:"Used in glass.",atomicRadius:87,electronegativity:2.04},
  {symbol:"C",name:"Carbon",number:6,group:14,period:2,category:"Reactive nonmetals",info:"Basis of life.",atomicRadius:67,electronegativity:2.55},
  {symbol:"N",name:"Nitrogen",number:7,group:15,period:2,category:"Reactive nonmetals",info:"78% of air.",atomicRadius:56,electronegativity:3.04},
  {symbol:"O",name:"Oxygen",number:8,group:16,period:2,category:"Reactive nonmetals",info:"Needed for breathing.",atomicRadius:48,electronegativity:3.44},
  {symbol:"F",name:"Fluorine",number:9,group:17,period:2,category:"Reactive nonmetals",info:"Most reactive.",atomicRadius:42,electronegativity:3.98},
  {symbol:"Ne",name:"Neon",number:10,group:18,period:2,category:"Noble gases",info:"Neon lights.",atomicRadius:38,electronegativity:null},
  {symbol:"Na",name:"Sodium",number:11,group:1,period:3,category:"Alkali metals",info:"Reacts with water.",atomicRadius:190,electronegativity:0.93},
  {symbol:"Mg",name:"Magnesium",number:12,group:2,period:3,category:"Alkaline earth metals",info:"In chlorophyll.",atomicRadius:145,electronegativity:1.31},
  {symbol:"Al",name:"Aluminum",number:13,group:13,period:3,category:"Post-transition metals",info:"Light metal.",atomicRadius:118,electronegativity:1.61},
  {symbol:"Si",name:"Silicon",number:14,group:14,period:3,category:"Metalloids",info:"Used in chips.",atomicRadius:111,electronegativity:1.90},
  {symbol:"P",name:"Phosphorus",number:15,group:15,period:3,category:"Reactive nonmetals",info:"Essential for life.",atomicRadius:98,electronegativity:2.19},
  {symbol:"S",name:"Sulfur",number:16,group:16,period:3,category:"Reactive nonmetals",info:"In volcanoes.",atomicRadius:88,electronegativity:2.58},
  {symbol:"Cl",name:"Chlorine",number:17,group:17,period:3,category:"Reactive nonmetals",info:"Water purification.",atomicRadius:79,electronegativity:3.16},
  {symbol:"Ar",name:"Argon",number:18,group:18,period:3,category:"Noble gases",info:"Noble gas.",atomicRadius:71,electronegativity:null},
  {symbol:"K",name:"Potassium",number:19,group:1,period:4,category:"Alkali metals",info:"Bananas.",atomicRadius:243,electronegativity:0.82},
  {symbol:"Ca",name:"Calcium",number:20,group:2,period:4,category:"Alkaline earth metals",info:"Bones/teeth.",atomicRadius:194,electronegativity:1.00},
  {symbol:"Sc",name:"Scandium",number:21,group:3,period:4,category:"Transition metals",info:"Transition metal.",atomicRadius:184,electronegativity:1.36},
  {symbol:"Ti",name:"Titanium",number:22,group:4,period:4,category:"Transition metals",info:"Strong metal.",atomicRadius:176,electronegativity:1.54},
  {symbol:"V",name:"Vanadium",number:23,group:5,period:4,category:"Transition metals",info:"Steel additive.",atomicRadius:171,electronegativity:1.63},
  {symbol:"Cr",name:"Chromium",number:24,group:6,period:4,category:"Transition metals",info:"Stainless steel.",atomicRadius:166,electronegativity:1.66},
  {symbol:"Mn",name:"Manganese",number:25,group:7,period:4,category:"Transition metals",info:"Steel making.",atomicRadius:161,electronegativity:1.55},
  {symbol:"Fe",name:"Iron",number:26,group:8,period:4,category:"Transition metals",info:"Steel.",atomicRadius:156,electronegativity:1.83},
  {symbol:"Co",name:"Cobalt",number:27,group:9,period:4,category:"Transition metals",info:"Magnets.",atomicRadius:152,electronegativity:1.88},
  {symbol:"Ni",name:"Nickel",number:28,group:10,period:4,category:"Transition metals",info:"Coins.",atomicRadius:149,electronegativity:1.91},
  {symbol:"Cu",name:"Copper",number:29,group:11,period:4,category:"Transition metals",info:"Wires.",atomicRadius:145,electronegativity:1.90},
  {symbol:"Zn",name:"Zinc",number:30,group:12,period:4,category:"Post-transition metals",info:"Galvanizing.",atomicRadius:142,electronegativity:1.65},
  {symbol:"Ga",name:"Gallium",number:31,group:13,period:4,category:"Post-transition metals",info:"Melts in hand.",atomicRadius:136,electronegativity:1.81},
  {symbol:"Ge",name:"Germanium",number:32,group:14,period:4,category:"Metalloids",info:"Semiconductors.",atomicRadius:125,electronegativity:2.01},
  {symbol:"As",name:"Arsenic",number:33,group:15,period:4,category:"Metalloids",info:"Poison.",atomicRadius:114,electronegativity:2.18},
  {symbol:"Se",name:"Selenium",number:34,group:16,period:4,category:"Reactive nonmetals",info:"Photocells.",atomicRadius:103,electronegativity:2.55},
  {symbol:"Br",name:"Bromine",number:35,group:17,period:4,category:"Reactive nonmetals",info:"Liquid halogen.",atomicRadius:94,electronegativity:2.96},
  {symbol:"Kr",name:"Krypton",number:36,group:18,period:4,category:"Noble gases",info:"Lights.",atomicRadius:88,electronegativity:3.00},
  {symbol:"Rb",name:"Rubidium",number:37,group:1,period:5,category:"Alkali metals",info:"Soft metal.",atomicRadius:265,electronegativity:0.82},
  {symbol:"Sr",name:"Strontium",number:38,group:2,period:5,category:"Alkaline earth metals",info:"Fireworks.",atomicRadius:219,electronegativity:0.95},
  {symbol:"Y",name:"Yttrium",number:39,group:3,period:5,category:"Transition metals",info:"LEDs.",atomicRadius:212,electronegativity:1.22},
  {symbol:"Zr",name:"Zirconium",number:40,group:4,period:5,category:"Transition metals",info:"Ceramics.",atomicRadius:206,electronegativity:1.33},
  {symbol:"Nb",name:"Niobium",number:41,group:5,period:5,category:"Transition metals",info:"Superconductors.",atomicRadius:198,electronegativity:1.6},
  {symbol:"Mo",name:"Molybdenum",number:42,group:6,period:5,category:"Transition metals",info:"Steel alloys.",atomicRadius:190,electronegativity:2.16},
  {symbol:"Tc",name:"Technetium",number:43,group:7,period:5,category:"Transition metals",info:"Radioactive.",atomicRadius:183,electronegativity:1.9},
  {symbol:"Ru",name:"Ruthenium",number:44,group:8,period:5,category:"Transition metals",info:"Electronics.",atomicRadius:178,electronegativity:2.2},
  {symbol:"Rh",name:"Rhodium",number:45,group:9,period:5,category:"Transition metals",info:"Catalysts.",atomicRadius:173,electronegativity:2.28},
  {symbol:"Pd",name:"Palladium",number:46,group:10,period:5,category:"Transition metals",info:"Jewelry.",atomicRadius:169,electronegativity:2.20},
  {symbol:"Ag",name:"Silver",number:47,group:11,period:5,category:"Transition metals",info:"Coins.",atomicRadius:165,electronegativity:1.93},
  {symbol:"Cd",name:"Cadmium",number:48,group:12,period:5,category:"Post-transition metals",info:"Batteries.",atomicRadius:161,electronegativity:1.69},
  {symbol:"In",name:"Indium",number:49,group:13,period:5,category:"Post-transition metals",info:"Touchscreens.",atomicRadius:156,electronegativity:1.78},
  {symbol:"Sn",name:"Tin",number:50,group:14,period:5,category:"Post-transition metals",info:"Cans.",atomicRadius:145,electronegativity:1.96},
  {symbol:"Sb",name:"Antimony",number:51,group:15,period:5,category:"Metalloids",info:"Flame retardant.",atomicRadius:133,electronegativity:2.05},
  {symbol:"Te",name:"Tellurium",number:52,group:16,period:5,category:"Metalloids",info:"Solar cells.",atomicRadius:123,electronegativity:2.10},
  {symbol:"I",name:"Iodine",number:53,group:17,period:5,category:"Reactive nonmetals",info:"Disinfectant.",atomicRadius:115,electronegativity:2.66},
  {symbol:"Xe",name:"Xenon",number:54,group:18,period:5,category:"Noble gases",info:"Headlights.",atomicRadius:108,electronegativity:2.6},
  {symbol:"Cs",name:"Cesium",number:55,group:1,period:6,category:"Alkali metals",info:"Atomic clocks.",atomicRadius:298,electronegativity:0.79},
  {symbol:"Ba",name:"Barium",number:56,group:2,period:6,category:"Alkaline earth metals",info:"X-rays.",atomicRadius:253,electronegativity:0.89},
  {symbol:"La",name:"Lanthanum",number:57,group:3,period:6,category:"Lanthanides",info:"Camera lenses.",atomicRadius:195,electronegativity:1.10},
  {symbol:"Ce",name:"Cerium",number:58,group:3,period:6,category:"Lanthanides",info:"Lighter flints.",atomicRadius:185,electronegativity:1.12},
  {symbol:"Pr",name:"Praseodymium",number:59,group:3,period:6,category:"Lanthanides",info:"Magnets.",atomicRadius:247,electronegativity:1.13},
  {symbol:"Nd",name:"Neodymium",number:60,group:3,period:6,category:"Lanthanides",info:"Strong magnets.",atomicRadius:206,electronegativity:1.14},
  {symbol:"Pm",name:"Promethium",number:61,group:3,period:6,category:"Lanthanides",info:"Radioactive.",atomicRadius:205,electronegativity:null},
  {symbol:"Sm",name:"Samarium",number:62,group:3,period:6,category:"Lanthanides",info:"Magnets.",atomicRadius:238,electronegativity:1.17},
  {symbol:"Eu",name:"Europium",number:63,group:3,period:6,category:"Lanthanides",info:"TV screens.",atomicRadius:231,electronegativity:null},
  {symbol:"Gd",name:"Gadolinium",number:64,group:3,period:6,category:"Lanthanides",info:"MRI contrast.",atomicRadius:233,electronegativity:1.20},
  {symbol:"Tb",name:"Terbium",number:65,group:3,period:6,category:"Lanthanides",info:"Green phosphor.",atomicRadius:225,electronegativity:null},
  {symbol:"Dy",name:"Dysprosium",number:66,group:3,period:6,category:"Lanthanides",info:"Magnets.",atomicRadius:228,electronegativity:1.22},
  {symbol:"Ho",name:"Holmium",number:67,group:3,period:6,category:"Lanthanides",info:"Magnets.",atomicRadius:226,electronegativity:1.23},
  {symbol:"Er",name:"Erbium",number:68,group:3,period:6,category:"Lanthanides",info:"Lasers.",atomicRadius:226,electronegativity:1.24},
  {symbol:"Tm",name:"Thulium",number:69,group:3,period:6,category:"Lanthanides",info:"Lasers.",atomicRadius:222,electronegativity:1.25},
  {symbol:"Yb",name:"Ytterbium",number:70,group:3,period:6,category:"Lanthanides",info:"Lasers.",atomicRadius:222,electronegativity:null},
  {symbol:"Lu",name:"Lutetium",number:71,group:3,period:6,category:"Lanthanides",info:"PET scans.",atomicRadius:217,electronegativity:1.27},
  {symbol:"Hf",name:"Hafnium",number:72,group:4,period:6,category:"Transition metals",info:"Nuclear reactors.",atomicRadius:208,electronegativity:1.3},
  {symbol:"Ta",name:"Tantalum",number:73,group:5,period:6,category:"Transition metals",info:"Electronics.",atomicRadius:200,electronegativity:1.5},
  {symbol:"W",name:"Tungsten",number:74,group:6,period:6,category:"Transition metals",info:"Light bulbs.",atomicRadius:193,electronegativity:2.36},
  {symbol:"Re",name:"Rhenium",number:75,group:7,period:6,category:"Transition metals",info:"Engines.",atomicRadius:188,electronegativity:1.9},
  {symbol:"Os",name:"Osmium",number:76,group:8,period:6,category:"Transition metals",info:"Densest element.",atomicRadius:185,electronegativity:2.2},
  {symbol:"Ir",name:"Iridium",number:77,group:9,period:6,category:"Transition metals",info:"Corrosion resistant.",atomicRadius:180,electronegativity:2.20},
  {symbol:"Pt",name:"Platinum",number:78,group:10,period:6,category:"Transition metals",info:"Jewelry.",atomicRadius:177,electronegativity:2.28},
  {symbol:"Au",name:"Gold",number:79,group:11,period:6,category:"Transition metals",info:"Money.",atomicRadius:174,electronegativity:2.54},
  {symbol:"Hg",name:"Mercury",number:80,group:12,period:6,category:"Post-transition metals",info:"Thermometers.",atomicRadius:171,electronegativity:2.00},
  {symbol:"Tl",name:"Thallium",number:81,group:13,period:6,category:"Post-transition metals",info:"Poison.",atomicRadius:156,electronegativity:1.62},
  {symbol:"Pb",name:"Lead",number:82,group:14,period:6,category:"Post-transition metals",info:"Old pipes.",atomicRadius:154,electronegativity:1.87},
  {symbol:"Bi",name:"Bismuth",number:83,group:15,period:6,category:"Post-transition metals",info:"Pepto-Bismol.",atomicRadius:143,electronegativity:2.02},
  {symbol:"Po",name:"Polonium",number:84,group:16,period:6,category:"Post-transition metals",info:"Radioactive.",atomicRadius:135,electronegativity:2.00},
  {symbol:"At",name:"Astatine",number:85,group:17,period:6,category:"Metalloids",info:"Rare halogen.",atomicRadius:127,electronegativity:2.2},
  {symbol:"Rn",name:"Radon",number:86,group:18,period:6,category:"Noble gases",info:"Radioactive gas.",atomicRadius:120,electronegativity:null},
  {symbol:"Fr",name:"Francium",number:87,group:1,period:7,category:"Alkali metals",info:"Radioactive.",atomicRadius:348,electronegativity:0.7},
  {symbol:"Ra",name:"Radium",number:88,group:2,period:7,category:"Alkaline earth metals",info:"Radioactive.",atomicRadius:283,electronegativity:0.9},
  {symbol:"Ac",name:"Actinium",number:89,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:195,electronegativity:1.1},
  {symbol:"Th",name:"Thorium",number:90,group:3,period:7,category:"Actinides",info:"Nuclear fuel.",atomicRadius:180,electronegativity:1.3},
  {symbol:"Pa",name:"Protactinium",number:91,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:161,electronegativity:1.5},
  {symbol:"U",name:"Uranium",number:92,group:3,period:7,category:"Actinides",info:"Nuclear fuel.",atomicRadius:152,electronegativity:1.38},
  {symbol:"Np",name:"Neptunium",number:93,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:153,electronegativity:1.36},
  {symbol:"Pu",name:"Plutonium",number:94,group:3,period:7,category:"Actinides",info:"Nuclear bombs.",atomicRadius:151,electronegativity:1.28},
  {symbol:"Am",name:"Americium",number:95,group:3,period:7,category:"Actinides",info:"Smoke detectors.",atomicRadius:150,electronegativity:1.13},
  {symbol:"Cm",name:"Curium",number:96,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:148,electronegativity:null},
  {symbol:"Bk",name:"Berkelium",number:97,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:147,electronegativity:null},
  {symbol:"Cf",name:"Californium",number:98,group:3,period:7,category:"Actinides",info:"Radiography.",atomicRadius:145,electronegativity:null},
  {symbol:"Es",name:"Einsteinium",number:99,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:144,electronegativity:null},
  {symbol:"Fm",name:"Fermium",number:100,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:143,electronegativity:null},
  {symbol:"Md",name:"Mendelevium",number:101,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:142,electronegativity:null},
  {symbol:"No",name:"Nobelium",number:102,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:140,electronegativity:null},
  {symbol:"Lr",name:"Lawrencium",number:103,group:3,period:7,category:"Actinides",info:"Radioactive.",atomicRadius:150,electronegativity:null},
  {symbol:"Rf",name:"Rutherfordium",number:104,group:4,period:7,category:"Transition metals",info:"Synthetic.",atomicRadius:157,electronegativity:null},
  {symbol:"Db",name:"Dubnium",number:105,group:5,period:7,category:"Transition metals",info:"Synthetic.",atomicRadius:149,electronegativity:null},
  {symbol:"Sg",name:"Seaborgium",number:106,group:6,period:7,category:"Transition metals",info:"Synthetic.",atomicRadius:143,electronegativity:null},
  {symbol:"Bh",name:"Bohrium",number:107,group:7,period:7,category:"Transition metals",info:"Synthetic.",atomicRadius:141,electronegativity:null},
  {symbol:"Hs",name:"Hassium",number:108,group:8,period:7,category:"Transition metals",info:"Synthetic.",atomicRadius:134,electronegativity:null},
  {symbol:"Mt",name:"Meitnerium",number:109,group:9,period:7,category:"Transition metals",info:"Synthetic.",atomicRadius:null,electronegativity:null},
  {symbol:"Ds",name:"Darmstadtium",number:110,group:10,period:7,category:"Transition metals",info:"Synthetic.",atomicRadius:null,electronegativity:null},
  {symbol:"Rg",name:"Roentgenium",number:111,group:11,period:7,category:"Transition metals",info:"Synthetic.",atomicRadius:null,electronegativity:null},
  {symbol:"Cn",name:"Copernicium",number:112,group:12,period:7,category:"Post-transition metals",info:"Synthetic.",atomicRadius:null,electronegativity:null},
  {symbol:"Nh",name:"Nihonium",number:113,group:13,period:7,category:"Post-transition metals",info:"Synthetic.",atomicRadius:null,electronegativity:null},
  {symbol:"Fl",name:"Flerovium",number:114,group:14,period:7,category:"Post-transition metals",info:"Synthetic.",atomicRadius:null,electronegativity:null},
  {symbol:"Mc",name:"Moscovium",number:115,group:15,period:7,category:"Post-transition metals",info:"Synthetic.",atomicRadius:null,electronegativity:null},
  {symbol:"Lv",name:"Livermorium",number:116,group:16,period:7,category:"Post-transition metals",info:"Synthetic.",atomicRadius:null,electronegativity:null},
  {symbol:"Ts",name:"Tennessine",number:117,group:17,period:7,category:"Reactive nonmetals",info:"Synthetic.",atomicRadius:null,electronegativity:null},
  {symbol:"Og",name:"Oganesson",number:118,group:18,period:7,category:"Noble gases",info:"Synthetic.",atomicRadius:null,electronegativity:null}
];
