const elements = [
  {symbol:"H",name:"Hydrogen",number:1,group:1,period:1,category:"Reactive nonmetals",atomicRadius:53,electronegativity:2.20,info:"Lightest element."},
  {symbol:"He",name:"Helium",number:2,group:18,period:1,category:"Noble gases",atomicRadius:31,electronegativity:null,info:"Noble gas."},
  {symbol:"Li",name:"Lithium",number:3,group:1,period:2,category:"Alkali metals",atomicRadius:167,electronegativity:0.98,info:"Used in batteries."},
  {symbol:"Be",name:"Beryllium",number:4,group:2,period:2,category:"Alkaline earth metals",atomicRadius:112,electronegativity:1.57,info:"Light metal."},
  {symbol:"B",name:"Boron",number:5,group:13,period:2,category:"Metalloids",atomicRadius:87,electronegativity:2.04,info:"Used in glass."},
  {symbol:"C",name:"Carbon",number:6,group:14,period:2,category:"Reactive nonmetals",atomicRadius:67,electronegativity:2.55,info:"Basis of life."},
  {symbol:"N",name:"Nitrogen",number:7,group:15,period:2,category:"Reactive nonmetals",atomicRadius:56,electronegativity:3.04,info:"78% of air."},
  {symbol:"O",name:"Oxygen",number:8,group:16,period:2,category:"Reactive nonmetals",atomicRadius:48,electronegativity:3.44,info:"Needed for breathing."},
  {symbol:"F",name:"Fluorine",number:9,group:17,period:2,category:"Reactive nonmetals",atomicRadius:42,electronegativity:3.98,info:"Most reactive."},
  {symbol:"Ne",name:"Neon",number:10,group:18,period:2,category:"Noble gases",atomicRadius:38,electronegativity:null,info:"Neon lights."},
  {symbol:"Na",name:"Sodium",number:11,group:1,period:3,category:"Alkali metals",atomicRadius:190,electronegativity:0.93,info:"Reacts with water."},
  {symbol:"Mg",name:"Magnesium",number:12,group:2,period:3,category:"Alkaline earth metals",atomicRadius:145,electronegativity:1.31,info:"In chlorophyll."},
  {symbol:"Al",name:"Aluminum",number:13,group:13,period:3,category:"Post-transition metals",atomicRadius:118,electronegativity:1.61,info:"Light metal."},
  {symbol:"Si",name:"Silicon",number:14,group:14,period:3,category:"Metalloids",atomicRadius:111,electronegativity:1.90,info:"Used in chips."},
  {symbol:"P",name:"Phosphorus",number:15,group:15,period:3,category:"Reactive nonmetals",atomicRadius:98,electronegativity:2.19,info:"Essential for life."},
  {symbol:"S",name:"Sulfur",number:16,group:16,period:3,category:"Reactive nonmetals",atomicRadius:88,electronegativity:2.58,info:"In volcanoes."},
  {symbol:"Cl",name:"Chlorine",number:17,group:17,period:3,category:"Reactive nonmetals",atomicRadius:79,electronegativity:3.16,info:"Water purification."},
  {symbol:"Ar",name:"Argon",number:18,group:18,period:3,category:"Noble gases",atomicRadius:71,electronegativity:null,info:"Noble gas."},
  {symbol:"K",name:"Potassium",number:19,group:1,period:4,category:"Alkali metals",atomicRadius:243,electronegativity:0.82,info:"Bananas."},
  {symbol:"Ca",name:"Calcium",number:20,group:2,period:4,category:"Alkaline earth metals",atomicRadius:194,electronegativity:1.00,info:"Bones/teeth."},
  {symbol:"Sc",name:"Scandium",number:21,group:3,period:4,category:"Transition metals",atomicRadius:184,electronegativity:1.36,info:"Transition metal."},
  {symbol:"Ti",name:"Titanium",number:22,group:4,period:4,category:"Transition metals",atomicRadius:176,electronegativity:1.54,info:"Strong metal."},
  {symbol:"V",name:"Vanadium",number:23,group:5,period:4,category:"Transition metals",atomicRadius:171,electronegativity:1.63,info:"Steel additive."},
  {symbol:"Cr",name:"Chromium",number:24,group:6,period:4,category:"Transition metals",atomicRadius:166,electronegativity:1.66,info:"Stainless steel."},
  {symbol:"Mn",name:"Manganese",number:25,group:7,period:4,category:"Transition metals",atomicRadius:161,electronegativity:1.55,info:"Steel making."},
  {symbol:"Fe",name:"Iron",number:26,group:8,period:4,category:"Transition metals",atomicRadius:156,electronegativity:1.83,info:"Steel."},
  {symbol:"Co",name:"Cobalt",number:27,group:9,period:4,category:"Transition metals",atomicRadius:152,electronegativity:1.88,info:"Magnets."},
  {symbol:"Ni",name:"Nickel",number:28,group:10,period:4,category:"Transition metals",atomicRadius:149,electronegativity:1.91,info:"Coins."},
  {symbol:"Cu",name:"Copper",number:29,group:11,period:4,category:"Transition metals",atomicRadius:145,electronegativity:1.90,info:"Wires."},
  {symbol:"Zn",name:"Zinc",number:30,group:12,period:4,category:"Post-transition metals",atomicRadius:142,electronegativity:1.65,info:"Galvanizing."},
  {symbol:"Ga",name:"Gallium",number:31,group:13,period:4,category:"Post-transition metals",atomicRadius:136,electronegativity:1.81,info:"Melts in hand."},
  {symbol:"Ge",name:"Germanium",number:32,group:14,period:4,category:"Metalloids",atomicRadius:125,electronegativity:2.01,info:"Semiconductors."},
  {symbol:"As",name:"Arsenic",number:33,group:15,period:4,category:"Metalloids",atomicRadius:114,electronegativity:2.18,info:"Poison."},
  {symbol:"Se",name:"Selenium",number:34,group:16,period:4,category:"Reactive nonmetals",atomicRadius:103,electronegativity:2.55,info:"Photocells."},
  {symbol:"Br",name:"Bromine",number:35,group:17,period:4,category:"Reactive nonmetals",atomicRadius:94,electronegativity:2.96,info:"Liquid halogen."},
  {symbol:"Kr",name:"Krypton",number:36,group:18,period:4,category:"Noble gases",atomicRadius:88,electronegativity:3.00,info:"Lights."},
  {symbol:"Rb",name:"Rubidium",number:37,group:1,period:5,category:"Alkali metals",atomicRadius:265,electronegativity:0.82,info:"Soft metal."},
  {symbol:"Sr",name:"Strontium",number:38,group:2,period:5,category:"Alkaline earth metals",atomicRadius:219,electronegativity:0.95,info:"Fireworks."},
  {symbol:"Y",name:"Yttrium",number:39,group:3,period:5,category:"Transition metals",atomicRadius:212,electronegativity:1.22,info:"LEDs."},
  {symbol:"Zr",name:"Zirconium",number:40,group:4,period:5,category:"Transition metals",atomicRadius:206,electronegativity:1.33,info:"Ceramics."},
  {symbol:"Nb",name:"Niobium",number:41,group:5,period:5,category:"Transition metals",atomicRadius:198,electronegativity:1.6,info:"Superconductors."},
  {symbol:"Mo",name:"Molybdenum",number:42,group:6,period:5,category:"Transition metals",atomicRadius:190,electronegativity:2.16,info:"Steel alloys."},
  {symbol:"Tc",name:"Technetium",number:43,group:7,period:5,category:"Transition metals",atomicRadius:183,electronegativity:1.9,info:"Radioactive."},
  {symbol:"Ru",name:"Ruthenium",number:44,group:8,period:5,category:"Transition metals",atomicRadius:178,electronegativity:2.2,info:"Electronics."},
  {symbol:"Rh",name:"Rhodium",number:45,group:9,period:5,category:"Transition metals",atomicRadius:173,electronegativity:2.28,info:"Catalysts."},
  {symbol:"Pd",name:"Palladium",number:46,group:10,period:5,category:"Transition metals",atomicRadius:169,electronegativity:2.20,info:"Jewelry."},
  {symbol:"Ag",name:"Silver",number:47,group:11,period:5,category:"Transition metals",atomicRadius:165,electronegativity:1.93,info:"Coins."},
  {symbol:"Cd",name:"Cadmium",number:48,group:12,period:5,category:"Post-transition metals",atomicRadius:161,electronegativity:1.69,info:"Batteries."},
  {symbol:"In",name:"Indium",number:49,group:13,period:5,category:"Post-transition metals",atomicRadius:156,electronegativity:1.78,info:"Touchscreens."},
  {symbol:"Sn",name:"Tin",number:50,group:14,period:5,category:"Post-transition metals",atomicRadius:145,electronegativity:1.96,info:"Cans."},
  {symbol:"Sb",name:"Antimony",number:51,group:15,period:5,category:"Metalloids",atomicRadius:133,electronegativity:2.05,info:"Flame retardant."},
  {symbol:"Te",name:"Tellurium",number:52,group:16,period:5,category:"Metalloids",atomicRadius:123,electronegativity:2.10,info:"Solar cells."},
  {symbol:"I",name:"Iodine",number:53,group:17,period:5,category:"Reactive nonmetals",atomicRadius:115,electronegativity:2.66,info:"Disinfectant."},
  {symbol:"Xe",name:"Xenon",number:54,group:18,period:5,category:"Noble gases",atomicRadius:108,electronegativity:2.6,info:"Headlights."},
  {symbol:"Cs",name:"Cesium",number:55,group:1,period:6,category:"Alkali metals",atomicRadius:298,electronegativity:0.79,info:"Atomic clocks."},
  {symbol:"Ba",name:"Barium",number:56,group:2,period:6,category:"Alkaline earth metals",atomicRadius:253,electronegativity:0.89,info:"X-rays."},
  {symbol:"La",name:"Lanthanum",number:57,group:3,period:6,category:"Lanthanides",atomicRadius:195,electronegativity:1.10,info:"Camera lenses."},
  {symbol:"Ce",name:"Cerium",number:58,group:3,period:6,category:"Lanthanides",atomicRadius:185,electronegativity:1.12,info:"Lighter flints."},
  {symbol:"Pr",name:"Praseodymium",number:59,group:3,period:6,category:"Lanthanides",atomicRadius:247,electronegativity:1.13,info:"Magnets."},
  {symbol:"Nd",name:"Neodymium",number:60,group:3,period:6,category:"Lanthanides",atomicRadius:206,electronegativity:1.14,info:"Strong magnets."},
  {symbol:"Pm",name:"Promethium",number:61,group:3,period:6,category:"Lanthanides",atomicRadius:205,electronegativity:null,info:"Radioactive."},
  {symbol:"Sm",name:"Samarium",number:62,group:3,period:6,category:"Lanthanides",atomicRadius:238,electronegativity:1.17,info:"Magnets."},
  {symbol:"Eu",name:"Europium",number:63,group:3,period:6,category:"Lanthanides",atomicRadius:231,electronegativity:null,info:"TV screens."},
  {symbol:"Gd",name:"Gadolinium",number:64,group:3,period:6,category:"Lanthanides",atomicRadius:233,electronegativity:1.20,info:"MRI contrast."},
  {symbol:"Tb",name:"Terbium",number:65,group:3,period:6,category:"Lanthanides",atomicRadius:225,electronegativity:null,info:"Green phosphor."},
  {symbol:"Dy",name:"Dysprosium",number:66,group:3,period:6,category:"Lanthanides",atomicRadius:228,electronegativity:1.22,info:"Magnets."},
  {symbol:"Ho",name:"Holmium",number:67,group:3,period:6,category:"Lanthanides",atomicRadius:226,electronegativity:1.23,info:"Magnets."},
  {symbol:"Er",name:"Erbium",number:68,group:3,period:6,category:"Lanthanides",atomicRadius:226,electronegativity:1.24,info:"Lasers."},
  {symbol:"Tm",name:"Thulium",number:69,group:3,period:6,category:"Lanthanides",atomicRadius:222,electronegativity:1.25,info:"Lasers."},
  {symbol:"Yb",name:"Ytterbium",number:70,group:3,period:6,category:"Lanthanides",atomicRadius:222,electronegativity:null,info:"Lasers."},
  {symbol:"Lu",name:"Lutetium",number:71,group:3,period:6,category:"Lanthanides",atomicRadius:217,electronegativity:1.27,info:"PET scans."},
  {symbol:"Hf",name:"Hafnium",number:72,group:4,period:6,category:"Transition metals",atomicRadius:208,electronegativity:1.3,info:"Nuclear reactors."},
  {symbol:"Ta",name:"Tantalum",number:73,group:5,period:6,category:"Transition metals",atomicRadius:200,electronegativity:1.5,info:"Electronics."},
  {symbol:"W",name:"Tungsten",number:74,group:6,period:6,category:"Transition metals",atomicRadius:193,electronegativity:2.36,info:"Light bulbs."},
  {symbol:"Re",name:"Rhenium",number:75,group:7,period:6,category:"Transition metals",atomicRadius:188,electronegativity:1.9,info:"Engines."},
  {symbol:"Os",name:"Osmium",number:76,group:8,period:6,category:"Transition metals",atomicRadius:185,electronegativity:2.2,info:"Densest element."},
  {symbol:"Ir",name:"Iridium",number:77,group:9,period:6,category:"Transition metals",atomicRadius:180,electronegativity:2.20,info:"Corrosion resistant."},
  {symbol:"Pt",name:"Platinum",number:78,group:10,period:6,category:"Transition metals",atomicRadius:177,electronegativity:2.28,info:"Jewelry."},
  {symbol:"Au",name:"Gold",number:79,group:11,period:6,category:"Transition metals",atomicRadius:174,electronegativity:2.54,info:"Money."},
  {symbol:"Hg",name:"Mercury",number:80,group:12,period:6,category:"Post-transition metals",atomicRadius:171,electronegativity:2.00,info:"Thermometers."},
  {symbol:"Tl",name:"Thallium",number:81,group:13,period:6,category:"Post-transition metals",atomicRadius:156,electronegativity:1.62,info:"Poison."},
  {symbol:"Pb",name:"Lead",number:82,group:14,period:6,category:"Post-transition metals",atomicRadius:154,electronegativity:2.33,info:"Toxic metal."},
  {symbol:"Bi",name:"Bismuth",number:83,group:15,period:6,category:"Post-transition metals",atomicRadius:143,electronegativity:2.02,info:"Medicinal use."},
  {symbol:"Po",name:"Polonium",number:84,group:16,period:6,category:"Post-transition metals",atomicRadius:135,electronegativity:2.0,info:"Radioactive."},
  {symbol:"At",name:"Astatine",number:85,group:17,period:6,category:"Metalloids",atomicRadius:127,electronegativity:2.2,info:"Rare halogen."},
  {symbol:"Rn",name:"Radon",number:86,group:18,period:6,category:"Noble gases",atomicRadius:120,electronegativity:null,info:"Radioactive gas."},
  {symbol:"Fr",name:"Francium",number:87,group:1,period:7,category:"Alkali metals",atomicRadius:348,electronegativity:0.7,info:"Rare, radioactive."},
  {symbol:"Ra",name:"Radium",number:88,group:2,period:7,category:"Alkaline earth metals",atomicRadius:283,electronegativity:0.9,info:"Radioactive."},
  {symbol:"Ac",name:"Actinium",number:89,group:3,period:7,category:"Actinides",atomicRadius:260,electronegativity:1.1,info:"Radioactive."},
  {symbol:"Th",name:"Thorium",number:90,group:3,period:7,category:"Actinides",atomicRadius:237,electronegativity:1.3,info:"Nuclear fuel."},
  {symbol:"Pa",name:"Protactinium",number:91,group:3,period:7,category:"Actinides",atomicRadius:243,electronegativity:1.5,info:"Radioactive."},
  {symbol:"U",name:"Uranium",number:92,group:3,period:7,category:"Actinides",atomicRadius:240,electronegativity:1.38,info:"Nuclear fuel."},
  {symbol:"Np",name:"Neptunium",number:93,group:3,period:7,category:"Actinides",atomicRadius:221,electronegativity:1.36,info:"Radioactive."},
  {symbol:"Pu",name:"Plutonium",number:94,group:3,period:7,category:"Actinides",atomicRadius:243,electronegativity:1.28,info:"Nuclear weapons."},
  {symbol:"Am",name:"Americium",number:95,group:3,period:7,category:"Actinides",atomicRadius:244,electronegativity:1.13,info:"Smoke detectors."},
  {symbol:"Cm",name:"Curium",number:96,group:3,period:7,category:"Actinides",atomicRadius:245,electronegativity:1.28,info:"Radioactive."},
  {symbol:"Bk",name:"Berkelium",number:97,group:3,period:7,category:"Actinides",atomicRadius:244,electronegativity:1.3,info:"Synthetic."},
  {symbol:"Cf",name:"Californium",number:98,group:3,period:7,category:"Actinides",atomicRadius:245,electronegativity:1.3,info:"Synthetic."},
  {symbol:"Es",name:"Einsteinium",number:99,group:3,period:7,category:"Actinides",atomicRadius:245,electronegativity:1.3,info:"Synthetic."},
  {symbol:"Fm",name:"Fermium",number:100,group:3,period:7,category:"Actinides",atomicRadius:245,electronegativity:1.3,info:"Synthetic."},
  {symbol:"Md",name:"Mendelevium",number:101,group:3,period:7,category:"Actinides",atomicRadius:246,electronegativity:1.3,info:"Synthetic."},
  {symbol:"No",name:"Nobelium",number:102,group:3,period:7,category:"Actinides",atomicRadius:246,electronegativity:1.3,info:"Synthetic."},
  {symbol:"Lr",name:"Lawrencium",number:103,group:3,period:7,category:"Actinides",atomicRadius:246,electronegativity:1.3,info:"Synthetic."},
  {symbol:"Rf",name:"Rutherfordium",number:104,group:4,period:7,category:"Transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Db",name:"Dubnium",number:105,group:5,period:7,category:"Transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Sg",name:"Seaborgium",number:106,group:6,period:7,category:"Transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Bh",name:"Bohrium",number:107,group:7,period:7,category:"Transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Hs",name:"Hassium",number:108,group:8,period:7,category:"Transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Mt",name:"Meitnerium",number:109,group:9,period:7,category:"Transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Ds",name:"Darmstadtium",number:110,group:10,period:7,category:"Transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Rg",name:"Roentgenium",number:111,group:11,period:7,category:"Transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Cn",name:"Copernicium",number:112,group:12,period:7,category:"Post-transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Nh",name:"Nihonium",number:113,group:13,period:7,category:"Post-transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Fl",name:"Flerovium",number:114,group:14,period:7,category:"Post-transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Mc",name:"Moscovium",number:115,group:15,period:7,category:"Post-transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Lv",name:"Livermorium",number:116,group:16,period:7,category:"Post-transition metals",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Ts",name:"Tennessine",number:117,group:17,period:7,category:"Metalloids",atomicRadius:150,electronegativity:null,info:"Synthetic."},
  {symbol:"Og",name:"Oganesson",number:118,group:18,period:7,category:"Noble gases",atomicRadius:150,electronegativity:null,info:"Synthetic."}
];
