// 118 element data for the periodic table
const elements = [
    {symbol: "H", name: "Hydrogen", number: 1, group: 1, period: 1, info: "Lightest element."},
    {symbol: "He", name: "Helium", number: 2, group: 18, period: 1, info: "Noble gas."},
    {symbol: "Li", name: "Lithium", number: 3, group: 1, period: 2, info: "Used in batteries."},
    {symbol: "Be", name: "Beryllium", number: 4, group: 2, period: 2, info: "Light metal."},
    {symbol: "B", name: "Boron", number: 5, group: 13, period: 2, info: "Used in glass."},
    {symbol: "C", name: "Carbon", number: 6, group: 14, period: 2, info: "Basis of life."},
    {symbol: "N", name: "Nitrogen", number: 7, group: 15, period: 2, info: "78% of air."},
    {symbol: "O", name: "Oxygen", number: 8, group: 16, period: 2, info: "Needed for breathing."},
    {symbol: "F", name: "Fluorine", number: 9, group: 17, period: 2, info: "Most reactive."},
    {symbol: "Ne", name: "Neon", number: 10, group: 18, period: 2, info: "Neon lights."},
    {symbol: "Na", name: "Sodium", number: 11, group: 1, period: 3, info: "Reacts with water."},
    {symbol: "Mg", name: "Magnesium", number: 12, group: 2, period: 3, info: "In chlorophyll."},
    {symbol: "Al", name: "Aluminum", number: 13, group: 13, period: 3, info: "Light metal."},
    {symbol: "Si", name: "Silicon", number: 14, group: 14, period: 3, info: "Used in chips."},
    {symbol: "P", name: "Phosphorus", number: 15, group: 15, period: 3, info: "Essential for life."},
    {symbol: "S", name: "Sulfur", number: 16, group: 16, period: 3, info: "In volcanoes."},
    {symbol: "Cl", name: "Chlorine", number: 17, group: 17, period: 3, info: "Water purification."},
    {symbol: "Ar", name: "Argon", number: 18, group: 18, period: 3, info: "Noble gas."},
    {symbol: "K", name: "Potassium", number: 19, group: 1, period: 4, info: "Bananas."},
    {symbol: "Ca", name: "Calcium", number: 20, group: 2, period: 4, info: "Bones/teeth."},
    {symbol: "Sc", name: "Scandium", number: 21, group: 3, period: 4, info: "Transition metal."},
    {symbol: "Ti", name: "Titanium", number: 22, group: 4, period: 4, info: "Strong metal."},
    {symbol: "V", name: "Vanadium", number: 23, group: 5, period: 4, info: "Steel additive."},
    {symbol: "Cr", name: "Chromium", number: 24, group: 6, period: 4, info: "Stainless steel."},
    {symbol: "Mn", name: "Manganese", number: 25, group: 7, period: 4, info: "Steel making."},
    {symbol: "Fe", name: "Iron", number: 26, group: 8, period: 4, info: "Steel."},
    {symbol: "Co", name: "Cobalt", number: 27, group: 9, period: 4, info: "Magnets."},
    {symbol: "Ni", name: "Nickel", number: 28, group: 10, period: 4, info: "Coins."},
    {symbol: "Cu", name: "Copper", number: 29, group: 11, period: 4, info: "Wires."},
    {symbol: "Zn", name: "Zinc", number: 30, group: 12, period: 4, info: "Galvanizing."},
    {symbol: "Ga", name: "Gallium", number: 31, group: 13, period: 4, info: "Melts in hand."},
    {symbol: "Ge", name: "Germanium", number: 32, group: 14, period: 4, info: "Semiconductors."},
    {symbol: "As", name: "Arsenic", number: 33, group: 15, period: 4, info: "Poison."},
    {symbol: "Se", name: "Selenium", number: 34, group: 16, period: 4, info: "Photocells."},
    {symbol: "Br", name: "Bromine", number: 35, group: 17, period: 4, info: "Liquid halogen."},
    {symbol: "Kr", name: "Krypton", number: 36, group: 18, period: 4, info: "Lights."},
    {symbol: "Rb", name: "Rubidium", number: 37, group: 1, period: 5, info: "Soft metal."},
    {symbol: "Sr", name: "Strontium", number: 38, group: 2, period: 5, info: "Fireworks."},
    {symbol: "Y", name: "Yttrium", number: 39, group: 3, period: 5, info: "LEDs."},
    {symbol: "Zr", name: "Zirconium", number: 40, group: 4, period: 5, info: "Ceramics."},
    {symbol: "Nb", name: "Niobium", number: 41, group: 5, period: 5, info: "Superconductors."},
    {symbol: "Mo", name: "Molybdenum", number: 42, group: 6, period: 5, info: "Steel alloys."},
    {symbol: "Tc", name: "Technetium", number: 43, group: 7, period: 5, info: "Radioactive."},
    {symbol: "Ru", name: "Ruthenium", number: 44, group: 8, period: 5, info: "Electronics."},
    {symbol: "Rh", name: "Rhodium", number: 45, group: 9, period: 5, info: "Catalysts."},
    {symbol: "Pd", name: "Palladium", number: 46, group: 10, period: 5, info: "Jewelry."},
    {symbol: "Ag", name: "Silver", number: 47, group: 11, period: 5, info: "Coins."},
    {symbol: "Cd", name: "Cadmium", number: 48, group: 12, period: 5, info: "Batteries."},
    {symbol: "In", name: "Indium", number: 49, group: 13, period: 5, info: "Touchscreens."},
    {symbol: "Sn", name: "Tin", number: 50, group: 14, period: 5, info: "Cans."},
    {symbol: "Sb", name: "Antimony", number: 51, group: 15, period: 5, info: "Flame retardant."},
    {symbol: "Te", name: "Tellurium", number: 52, group: 16, period: 5, info: "Solar cells."},
    {symbol: "I", name: "Iodine", number: 53, group: 17, period: 5, info: "Disinfectant."},
    {symbol: "Xe", name: "Xenon", number: 54, group: 18, period: 5, info: "Headlights."},
    {symbol: "Cs", name: "Cesium", number: 55, group: 1, period: 6, info: "Atomic clocks."},
    {symbol: "Ba", name: "Barium", number: 56, group: 2, period: 6, info: "X-rays."},
    // Lanthanides
    {symbol: "La", name: "Lanthanum", number: 57, group: 3, period: 6, info: "Camera lenses."},
    {symbol: "Ce", name: "Cerium", number: 58, group: 3, period: 6, info: "Lighter flints."},
    {symbol: "Pr", name: "Praseodymium", number: 59, group: 3, period: 6, info: "Magnets."},
    {symbol: "Nd", name: "Neodymium", number: 60, group: 3, period: 6, info: "Strong magnets."},
    {symbol: "Pm", name: "Promethium", number: 61, group: 3, period: 6, info: "Radioactive."},
    {symbol: "Sm", name: "Samarium", number: 62, group: 3, period: 6, info: "Magnets."},
    {symbol: "Eu", name: "Europium", number: 63, group: 3, period: 6, info: "TV screens."},
    {symbol: "Gd", name: "Gadolinium", number: 64, group: 3, period: 6, info: "MRI contrast."},
    {symbol: "Tb", name: "Terbium", number: 65, group: 3, period: 6, info: "Green phosphor."},
    {symbol: "Dy", name: "Dysprosium", number: 66, group: 3, period: 6, info: "Magnets."},
    {symbol: "Ho", name: "Holmium", number: 67, group: 3, period: 6, info: "Magnets."},
    {symbol: "Er", name: "Erbium", number: 68, group: 3, period: 6, info: "Lasers."},
    {symbol: "Tm", name: "Thulium", number: 69, group: 3, period: 6, info: "Lasers."},
    {symbol: "Yb", name: "Ytterbium", number: 70, group: 3, period: 6, info: "Lasers."},
    {symbol: "Lu", name: "Lutetium", number: 71, group: 3, period: 6, info: "PET scans."},
    // End Lanthanides
    {symbol: "Hf", name: "Hafnium", number: 72, group: 4, period: 6, info: "Nuclear reactors."},
    {symbol: "Ta", name: "Tantalum", number: 73, group: 5, period: 6, info: "Electronics."},
    {symbol: "W", name: "Tungsten", number: 74, group: 6, period: 6, info: "Light bulbs."},
    {symbol: "Re", name: "Rhenium", number: 75, group: 7, period: 6, info: "Engines."},
    {symbol: "Os", name: "Osmium", number: 76, group: 8, period: 6, info: "Densest element."},
    {symbol: "Ir", name: "Iridium", number: 77, group: 9, period: 6, info: "Corrosion resistant."},
    {symbol: "Pt", name: "Platinum", number: 78, group: 10, period: 6, info: "Jewelry."},
    {symbol: "Au", name: "Gold", number: 79, group: 11, period: 6, info: "Money."},
    {symbol: "Hg", name: "Mercury", number: 80, group: 12, period: 6, info: "Thermometers."},
    {symbol: "Tl", name: "Thallium", number: 81, group: 13, period: 6, info: "Poison."},
    {symbol: "Pb", name: "Lead", number: 82, group: 14, period: 6, info: "Old pipes."},
    {symbol: "Bi", name: "Bismuth", number: 83, group: 15, period: 6, info: "Pepto-Bismol."},
    {symbol: "Po", name: "Polonium", number: 84, group: 16, period: 6, info: "Radioactive."},
    {symbol: "At", name: "Astatine", number: 85, group: 17, period: 6, info: "Rare halogen."},
    {symbol: "Rn", name: "Radon", number: 86, group: 18, period: 6, info: "Radioactive gas."},
    {symbol: "Fr", name: "Francium", number: 87, group: 1, period: 7, info: "Radioactive."},
    {symbol: "Ra", name: "Radium", number: 88, group: 2, period: 7, info: "Radioactive."},
    // Actinides
    {symbol: "Ac", name: "Actinium", number: 89, group: 3, period: 7, info: "Radioactive."},
    {symbol: "Th", name: "Thorium", number: 90, group: 3, period: 7, info: "Nuclear fuel."},
    {symbol: "Pa", name: "Protactinium", number: 91, group: 3, period: 7, info: "Radioactive."},
    {symbol: "U", name: "Uranium", number: 92, group: 3, period: 7, info: "Nuclear fuel."},
    {symbol: "Np", name: "Neptunium", number: 93, group: 3, period: 7, info: "Radioactive."},
    {symbol: "Pu", name: "Plutonium", number: 94, group: 3, period: 7, info: "Nuclear bombs."},
    {symbol: "Am", name: "Americium", number: 95, group: 3, period: 7, info: "Smoke detectors."},
    {symbol: "Cm", name: "Curium", number: 96, group: 3, period: 7, info: "Radioactive."},
    {symbol: "Bk", name: "Berkelium", number: 97, group: 3, period: 7, info: "Radioactive."},
    {symbol: "Cf", name: "Californium", number: 98, group: 3, period: 7, info: "Radiography."},
    {symbol: "Es", name: "Einsteinium", number: 99, group: 3, period: 7, info: "Radioactive."},
    {symbol: "Fm", name: "Fermium", number: 100, group: 3, period: 7, info: "Radioactive."},
    {symbol: "Md", name: "Mendelevium", number: 101, group: 3, period: 7, info: "Radioactive."},
    {symbol: "No", name: "Nobelium", number: 102, group: 3, period: 7, info: "Radioactive."},
    {symbol: "Lr", name: "Lawrencium", number: 103, group: 3, period: 7, info: "Radioactive."},
    // End Actinides
    {symbol: "Rf", name: "Rutherfordium", number: 104, group: 4, period: 7, info: "Synthetic."},
    {symbol: "Db", name: "Dubnium", number: 105, group: 5, period: 7, info: "Synthetic."},
    {symbol: "Sg", name: "Seaborgium", number: 106, group: 6, period: 7, info: "Synthetic."},
    {symbol: "Bh", name: "Bohrium", number: 107, group: 7, period: 7, info: "Synthetic."},
    {symbol: "Hs", name: "Hassium", number: 108, group: 8, period: 7, info: "Synthetic."},
    {symbol: "Mt", name: "Meitnerium", number: 109, group: 9, period: 7, info: "Synthetic."},
    {symbol: "Ds", name: "Darmstadtium", number: 110, group: 10, period: 7, info: "Synthetic."},
    {symbol: "Rg", name: "Roentgenium", number: 111, group: 11, period: 7, info: "Synthetic."},
    {symbol: "Cn", name: "Copernicium", number: 112, group: 12, period: 7, info: "Synthetic."},
    {symbol: "Fl", name: "Flerovium", number: 114, group: 14, period: 7, info: "Synthetic."},
    {symbol: "Lv", name: "Livermorium", number: 116, group: 16, period: 7, info: "Synthetic."},
    {symbol: "Ts", name: "Tennessine", number: 117, group: 17, period: 7, info: "Synthetic."},
    {symbol: "Og", name: "Oganesson", number: 118, group: 18, period: 7, info: "Synthetic."},
    // Some elements (113, 115) are missing group numbers; assign closest values for display
    {symbol: "Nh", name: "Nihonium", number: 113, group: 13, period: 7, info: "Synthetic."},
    {symbol: "Mc", name: "Moscovium", number: 115, group: 15, period: 7, info: "Synthetic."},
];
